[package]
name = "meln_graphics"
version = "0.1.0"
authors = ["alex13sh <alex97sh@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git="https://github.com/hecrj/iced", rev="9ba4cfd23f4620bab93df9616617643604db2c79",  features = ["canvas", "tokio", "svg"] }
iced_native = { git="https://github.com/hecrj/iced", rev="9ba4cfd23f4620bab93df9616617643604db2c79"}

chrono = "0.4"

log = {path = "./log"}
modbus = {path = "./modbus"}

[dependencies.plotters]
#path = "../plotters"
version = "*"
optional = true
default-features = false
features = ["image_encoder", "chrono", "line_series", "svg"] # "iced_back"]

[workspace]
members = [
    "log",
    "modbus",
]

[features]
default = ["plotters"]
