[package]
name = "meln_graphics"
version = "0.1.0"
authors = ["alex13sh <alex97sh@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { path = "../iced/", features = ["canvas", "tokio"]}
iced_native = { path = "../iced/native" }
iced_graphics = { path = "../iced/graphics" }

chrono = "0.4"
