[package]
name = "meln_graphics"
version = "0.1.0"
authors = ["alex13sh <alex97sh@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.2",  features = ["canvas", "tokio", "svg"] }
iced_native = { version = "0.2"}

chrono = "0.4"
coarse-prof = {version = "0.2.4"} #, path = "../coarse-prof-0.2.4"}

log = {path = "./log"}
modbus = {path = "./modbus"}
graphic = {path = "./graphic"}

[workspace]
members = [
    "log",
    "modbus",
]

[features]
default = ["graphic/plotters", "graphic/iced_backend"] #, "test"]

test = ["modbus/test"]

# [profile.release]
# debug = true
