[package]
name = "meln_graphics"
version = "0.1.0"
authors = ["alex13sh <alex97sh@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.2",  features = ["canvas", "tokio", "svg"] }
iced_native = { version = "0.2"}

futures = "0.3.12"
chrono = "0.4"
coarse-prof = {version = "0.2.4", path = "../coarse-prof-0.2.4"}
# log = "0.4.0"
env_logger = "0.8.2"

log = {path = "./log"}
modbus = {path = "./modbus"}

[dependencies.plotters]
#path = "../plotters"
version = "0.3.0"
optional = true
default-features = false
features = [ "chrono", "line_series", "svg_backend"] # "iced_back"]

[dependencies.iced_backend]
path = "./src/iced_backend/"
optional = true

[workspace]
members = [
    "log",
    "modbus",
]

[features]
default = ["plotters", "iced_backend"] #, "test"]

test = ["modbus/test"]

# [profile.release]
# debug = true
